# Generated by Django 3.2.6 on 2021-09-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_user_is_account_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
