# Generated by Django 3.2.6 on 2021-09-16 22:14

import apps.users_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users_app.models.upload_to),
        ),
    ]
