# Generated by Django 3.2.6 on 2022-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_project_color'),
        ('users_app', '0007_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faviroute_projects',
            field=models.ManyToManyField(blank=True, to='projects_app.project'),
        ),
    ]
