# Generated by Django 3.2.6 on 2022-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_project_color'),
        ('users_app', '0008_userprofile_faviroute_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faviroute_projects',
            field=models.ManyToManyField(blank=True, related_name='faviroute_projects', to='projects_app.project'),
        ),
    ]
