# Generated by Django 3.2.6 on 2022-02-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0004_auto_20220204_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='extra_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_extra_fields', to='tickets_app.extrafield'),
        ),
    ]
