# Generated by Django 3.2.6 on 2022-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0009_auto_20220204_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='color',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
