# Generated by Django 3.2.6 on 2022-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0010_extrafield_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='field_option_id',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
