# Generated by Django 3.2.6 on 2022-02-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_project_color'),
        ('tickets_app', '0011_extrafield_field_option_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects_app.project'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects_app.project'),
        ),
    ]
