# Generated by Django 3.2.6 on 2022-02-23 10:15

from django.db import migrations
from django.apps import apps as my_apps

class Migration(migrations.Migration):

    def make_many_projects(apps, schema_editor):
        """
            Adds the project object in ticket.project to the
            many-to-many relationship in ticket.projects
        """
        Ticket = my_apps.get_model('tickets_app', 'Ticket')

        for ticket in Ticket.objects.all():
            ticket.projects.add(ticket.project)

    dependencies = [
        ('tickets_app', '0012_auto_20220223_1015'),
    ]

    operations = [
        migrations.RunPython(make_many_projects),
    ]
