# Generated by Django 3.2.6 on 2022-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_project_color'),
        ('tickets_app', '0013_auto_20220223_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='project_tickets', to='projects_app.project'),
        ),
    ]
