# Generated by Django 3.2.6 on 2022-02-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_section_app', '0002_alter_section_project'),
        ('tickets_app', '0014_alter_ticket_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='section_tickets', to='task_section_app.Section'),
        ),
    ]
