# Generated by Django 3.2.6 on 2021-09-11 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_project_title'),
        ('task_section_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects_app.project'),
        ),
    ]
