# Generated by Django 3.2.6 on 2021-09-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='#000', max_length=20, null=True),
        ),
    ]
